valid_email = '********@gmail.com' #валидные данные скрыты
valid_phone = '+7(9***)8****54' #валидные данные скрыты
valid_password = '**123456789' #валидные данные скрыты
valid_login = '***ami' #валидные данные скрыты
valid_ls = '***8337741***' #валидные данные скрыты
valid_username = u"Окамов"
ad_slogan = u"Персональный помощник в цифровом мире Ростелекома"
site = 'https://b2c.passport.rt.ru'
link_lk = "/account_b2c/page"
drv_path = 'С:***//PycharmProjects/Driver/chromedriver.exe '
